package com.chris.league.utils

import com.chris.league.model.TeamModel
import com.chris.league.source.dto.TeamResDTO

fun List<TeamResDTO>.toListTeamModel(): List<TeamModel> {
    return map { it.toTeamModel() }.sortedBy { it.strTeam }
}

fun TeamResDTO.toTeamModel(): TeamModel = TeamModel(
    idAPIFootball = idAPIFootball,
    idLeague = idLeague,
    idLeague2 = idLeague2 ?: 0,
    idLeague3 = idLeague3 ?: 0,
    idLeague4 = idLeague4 ?: 0,
    idLeague5 = idLeague5 ?: 0,
    idLeague6 = idLeague6 ?: 0,
    idLeague7 = idLeague7 ?: 0,
    idSoccerXML = idSoccerXML,
    idTeam = idTeam,
    intFormedYear = intFormedYear,
    intLoved = intLoved ?: 0,
    intStadiumCapacity = intStadiumCapacity,
    strAlternate = strAlternate ?: "",
    strCountry = strCountry ?: "",
    strDescriptionCN = strDescriptionCN ?: "",
    strDescriptionDE = strDescriptionDE ?: "",
    strDescriptionEN = strDescriptionEN ?: "",
    strDescriptionES = strDescriptionES ?: "",
    strDescriptionFR = strDescriptionFR ?: "",
    strDescriptionHU = strDescriptionHU ?: "",
    strDescriptionIL = strDescriptionIL ?: "",
    strDescriptionIT = strDescriptionIT ?: "",
    strDescriptionJP = strDescriptionJP ?: "",
    strDescriptionNL = strDescriptionNL ?: "",
    strDescriptionNO = strDescriptionNO ?: "",
    strDescriptionPL = strDescriptionPL ?: "",
    strDescriptionPT = strDescriptionPT ?: "",
    strDescriptionRU = strDescriptionRU ?: "",
    strDescriptionSE = strDescriptionSE ?: "",
    strDivision = strDivision ?: "",
    strFacebook = strFacebook ?: "",
    strGender = strGender ?: "",
    strInstagram = strInstagram ?: "",
    strKeywords = strKeywords ?: "",
    strLeague = strLeague ?: "",
    strLeague2 = strLeague2 ?: "",
    strLeague3 = strLeague3 ?: "",
    strLeague4 = strLeague4 ?: "",
    strLeague5 = strLeague5 ?: "",
    strLeague6 = strLeague6 ?: "",
    strLeague7 = strLeague7 ?: "",
    strLocked = strLocked ?: "",
    strManager = strManager ?: "",
    strRSS = strRSS ?: "",
    strSport = strSport ?: "",
    strStadium = strStadium ?: "",
    strStadiumDescription = strStadiumDescription ?: "",
    strStadiumLocation = strStadiumLocation ?: "",
    strStadiumThumb = strStadiumThumb ?: "",
    strTeam = strTeam ?: "",
    strTeamBadge = strTeamBadge ?: "",
    strTeamBanner = strTeamBanner ?: "",
    strTeamFanart1 = strTeamFanart1 ?: "",
    strTeamFanart2 = strTeamFanart2 ?: "",
    strTeamFanart3 = strTeamFanart3 ?: "",
    strTeamFanart4 = strTeamFanart4 ?: "",
    strTeamJersey = strTeamJersey ?: "",
    strTeamLogo = strTeamLogo ?: "",
    strTeamShort = strTeamShort ?: "",
    strTwitter = strTwitter ?: "",
    strWebsite = strWebsite ?: "",
    strYoutube = strYoutube ?: "",
)