package com.chris.league.utils

import com.chris.league.model.EventModel
import com.chris.league.model.LeagueModel
import com.chris.league.model.TeamModel
import com.chris.league.source.dto.LeagueResDTO
import com.chris.league.source.dto.ResultEventResDTO
import com.chris.league.source.dto.TeamResDTO

fun List<TeamResDTO>.toListTeamModel(): List<TeamModel> {
    return map { it.toTeamModel() }.sortedBy { it.strTeam }
}

fun TeamResDTO.toTeamModel(): TeamModel = TeamModel(
    idAPIFootball = idAPIFootball,
    idLeague = idLeague,
    idLeague2 = idLeague2 ?: 0,
    idLeague3 = idLeague3 ?: 0,
    idLeague4 = idLeague4 ?: 0,
    idLeague5 = idLeague5 ?: 0,
    idLeague6 = idLeague6 ?: 0,
    idLeague7 = idLeague7 ?: 0,
    idSoccerXML = idSoccerXML ?: 0,
    idTeam = idTeam,
    intFormedYear = intFormedYear,
    intLoved = intLoved ?: 0,
    intStadiumCapacity = intStadiumCapacity,
    strAlternate = strAlternate ?: "",
    strCountry = strCountry ?: "",
    strDescriptionCN = strDescriptionCN ?: "",
    strDescriptionDE = strDescriptionDE ?: "",
    strDescriptionEN = strDescriptionEN ?: "",
    strDescriptionES = strDescriptionES ?: "",
    strDescriptionFR = strDescriptionFR ?: "",
    strDescriptionHU = strDescriptionHU ?: "",
    strDescriptionIL = strDescriptionIL ?: "",
    strDescriptionIT = strDescriptionIT ?: "",
    strDescriptionJP = strDescriptionJP ?: "",
    strDescriptionNL = strDescriptionNL ?: "",
    strDescriptionNO = strDescriptionNO ?: "",
    strDescriptionPL = strDescriptionPL ?: "",
    strDescriptionPT = strDescriptionPT ?: "",
    strDescriptionRU = strDescriptionRU ?: "",
    strDescriptionSE = strDescriptionSE ?: "",
    strDivision = strDivision ?: "",
    strFacebook = strFacebook ?: "",
    strGender = strGender ?: "",
    strInstagram = strInstagram ?: "",
    strKeywords = strKeywords ?: "",
    strLeague = strLeague ?: "",
    strLeague2 = strLeague2 ?: "",
    strLeague3 = strLeague3 ?: "",
    strLeague4 = strLeague4 ?: "",
    strLeague5 = strLeague5 ?: "",
    strLeague6 = strLeague6 ?: "",
    strLeague7 = strLeague7 ?: "",
    strLocked = strLocked ?: "",
    strManager = strManager ?: "",
    strRSS = strRSS ?: "",
    strSport = strSport ?: "",
    strStadium = strStadium ?: "",
    strStadiumDescription = strStadiumDescription ?: "",
    strStadiumLocation = strStadiumLocation ?: "",
    strStadiumThumb = strStadiumThumb ?: "",
    strTeam = strTeam ?: "",
    strTeamBadge = strTeamBadge ?: "",
    strTeamBanner = strTeamBanner ?: "",
    strTeamFanart1 = strTeamFanart1 ?: "",
    strTeamFanart2 = strTeamFanart2 ?: "",
    strTeamFanart3 = strTeamFanart3 ?: "",
    strTeamFanart4 = strTeamFanart4 ?: "",
    strTeamJersey = strTeamJersey ?: "",
    strTeamLogo = strTeamLogo ?: "",
    strTeamShort = strTeamShort ?: "",
    strTwitter = strTwitter ?: "",
    strWebsite = strWebsite ?: "",
    strYoutube = strYoutube ?: "",
)

fun List<LeagueResDTO>.toListLeagueModel(): List<LeagueModel> {
    return map { it.toLeagueModel() }
        .sortedBy { it.strLeague }
        .filter { it.strSport == Constants.SPORT }
}

fun LeagueResDTO.toLeagueModel(): LeagueModel = LeagueModel(
    idLeague = idLeague,
    strLeague = strLeague,
    strLeagueAlternate = strLeagueAlternate ?: "",
    strSport = strSport,
)

fun List<ResultEventResDTO>.toListEventModel(): List<EventModel> {
    return map { it.toEventModel() }.sortedBy { it.dateEvent }
}

fun ResultEventResDTO.toEventModel(): EventModel = EventModel(
    idEvent = idEvent,
    dateEvent = dateEvent,
    dateEventLocal = dateEventLocal ?: "",
    idAPIFootball = idAPIFootball ?: 0,
    idAwayTeam = idAwayTeam ?: 0,
    idHomeTeam = idHomeTeam ?: 0,
    idLeague = idLeague ?: 0,
    idSoccerXML = idSoccerXML ?: 0,
    intAwayScore = intAwayScore ?: 0,
    intAwayShots = intAwayShots ?: 0,
    intHomeScore = intHomeScore ?: 0,
    intHomeShots = intHomeShots ?: 0,
    intRound = intRound ?: 0,
    intSpectators = intSpectators ?: 0,
    strAwayFormation = strAwayFormation ?: "",
    strAwayGoalDetails = strAwayGoalDetails ?: "",
    strAwayLineupDefense = strAwayLineupDefense ?: "",
    strAwayLineupForward = strAwayLineupForward ?: "",
    strAwayLineupGoalkeeper = strAwayLineupGoalkeeper ?: "",
    strAwayLineupMidfield = strAwayLineupMidfield ?: "",
    strAwayLineupSubstitutes = strAwayLineupSubstitutes ?: "",
    strAwayRedCards = strAwayRedCards ?: "",
    strAwayTeam = strAwayTeam ?: "",
    strAwayYellowCards = strAwayYellowCards ?: "",
    strBanner = strBanner ?: "",
    strCity = strCity ?: "",
    strCountry = strCountry ?: "",
    strDescriptionEN = strDescriptionEN ?: "",
    strEvent = strEvent ?: "",
    strEventAlternate = strEventAlternate ?: "",
    strFanart = strFanart ?: "",
    strFilename = strFilename ?: "",
    strHomeFormation = strHomeFormation ?: "",
    strHomeGoalDetails = strHomeGoalDetails ?: "",
    strHomeLineupDefense = strHomeLineupDefense ?: "",
    strHomeLineupForward = strHomeLineupForward ?: "",
    strHomeLineupGoalkeeper = strHomeLineupGoalkeeper ?: "",
    strHomeLineupMidfield = strHomeLineupMidfield ?: "",
    strHomeLineupSubstitutes = strHomeLineupSubstitutes ?: "",
    strHomeRedCards = strHomeRedCards ?: "",
    strHomeTeam = strHomeTeam ?: "",
    strHomeYellowCards = strHomeYellowCards ?: "",
    strLeague = strLeague ?: "",
    strLocked = strLocked ?: "",
    strMap = strMap ?: "",
    strOfficial = strOfficial ?: "",
    strPoster = strPoster ?: "",
    strPostponed = strPostponed ?: "",
    strResult = strResult ?: "",
    strSeason = strSeason ?: "",
    strSport = strSport ?: "",
    strSquare = strSquare ?: "",
    strStatus = strStatus ?: "",
    strTVStation = strTVStation ?: "",
    strThumb = strThumb ?: "",
    strTime = strTime ?: "",
    strTimeLocal = strTimeLocal ?: "",
    strTimestamp = strTimestamp ?: "",
    strTweet1 = strTweet1 ?: "",
    strTweet2 = strTweet2 ?: "",
    strTweet3 = strTweet3 ?: "",
    strVenue = strVenue ?: "",
    strVideo = strVideo ?: "",
)